# Generated by Django 3.1.5 on 2021-02-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=500)),
                ('Confirmpassword', models.CharField(max_length=500)),
            ],
        ),
    ]
