# Generated by Django 3.1.5 on 2021-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stdacd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Sscqual', models.CharField(max_length=50)),
                ('Sscname', models.CharField(max_length=50)),
                ('Sscdate', models.CharField(max_length=10, null=True)),
                ('Sscmarks', models.CharField(max_length=10)),
                ('Sscgrading', models.CharField(max_length=50, null=True)),
                ('SscDoc', models.FileField(upload_to='')),
                ('Intqual', models.CharField(max_length=50)),
                ('Intname', models.CharField(max_length=50)),
                ('Intdate', models.CharField(max_length=10, null=True)),
                ('Intmarks', models.CharField(max_length=10)),
                ('Intgrading', models.CharField(max_length=50, null=True)),
                ('IntDoc', models.FileField(upload_to='')),
                ('Uniqual', models.CharField(max_length=50)),
                ('Uniname', models.CharField(max_length=50)),
                ('Unicname', models.CharField(max_length=50)),
                ('Unidate', models.CharField(max_length=10, null=True)),
                ('Unimarks', models.CharField(max_length=10)),
                ('Unigrading', models.CharField(max_length=50, null=True)),
                ('UniDoc', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stdcour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Applyingfor', models.CharField(max_length=50, null=True)),
                ('Date', models.CharField(max_length=50)),
                ('pcoun1', models.CharField(max_length=50)),
                ('pcoun2', models.CharField(max_length=50)),
                ('pcoun3', models.CharField(max_length=50)),
                ('pcour4', models.CharField(max_length=50)),
                ('pcour5', models.CharField(max_length=50)),
                ('pcour6', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stdind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=500)),
                ('Lastname', models.CharField(max_length=500)),
                ('Dateofbirth', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=50, null=True)),
                ('Maritial', models.CharField(max_length=50, null=True)),
                ('Nationality', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stdpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Testeng', models.CharField(max_length=50, null=True)),
                ('Yeareng', models.CharField(max_length=10, null=True)),
                ('Overallscoreeng', models.CharField(max_length=10, null=True)),
                ('Uploadeng', models.FileField(null=True, upload_to='')),
                ('Testad', models.CharField(max_length=50, null=True)),
                ('Yearad', models.CharField(max_length=10, null=True)),
                ('Overallscoread', models.CharField(max_length=10, null=True)),
                ('Uploadad', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
