# Generated by Django 3.1.5 on 2021-02-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_stdacd_stdcour_stdind_stdpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdind',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Firstname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Phonenumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
