# Generated by Django 3.1.5 on 2021-02-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_auto_20210222_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdacd',
            name='Intmarks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intqual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscmarks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscqual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Unicname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Uniname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Uniqual',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
