# Generated by Django 3.1.5 on 2021-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_auto_20210222_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdcour',
            name='Date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcoun1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcoun2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcoun3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcour4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcour5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcour6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
