# Generated by Django 3.1.4 on 2021-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_auto_20210222_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stdpro1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Testad', models.CharField(max_length=50, null=True)),
                ('Yearad', models.CharField(max_length=10, null=True)),
                ('Overallscoread', models.CharField(max_length=10, null=True)),
                ('Uploadad', models.FileField(null=True, upload_to='')),
                ('Urlad', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stdpro',
            old_name='Overallscoread',
            new_name='Urleng',
        ),
        migrations.RemoveField(
            model_name='stdpro',
            name='Testad',
        ),
        migrations.RemoveField(
            model_name='stdpro',
            name='Uploadad',
        ),
        migrations.RemoveField(
            model_name='stdpro',
            name='Yearad',
        ),
    ]
